### PR TITLE
Unify template settings

### LINKED ISSUE #18: Add a default `.gitignore` file to the template
I was pushing a repo created by `create-ink-app` & it was pushing `node_modules`. I quickly noticed it doesn't have its own `.gitignore`.

I think a `.gitignore` file should exist by default. I personally prefer using a `.gitignore` generated by `npx gitignore node`.

### PR DESCRIPTION
**Pull request by LitoMore**
Fixes #18 

### Changes

- Add `.gitignore` to `template/js`
- Drop `.gitattributes` from `template/ts`
- Remove `yarn.lock` from `template/ts/.gitingore`

Just to unify those template settings.

### CODE REVIEW

**Comment by vadimdemedes** [comment]
Why remove `.editorconfig`?

**Comment by LitoMore** [comment]
The `js` template does not have `.editorconfig` either.

And we don't need them right? We should let users choose what format to use.

**Review by mattferrin — COMMENTED** [review]
These changes make sense to me now and I like them.

**Comment by sunflowermarmalade** [comment]
Will these changes be merged to the master branch?

**Comment by vadimdemedes** [comment]
Sorry, but I have to close this in favor of https://github.com/vadimdemedes/create-ink-app/commit/d187e07977ed82531c030e174d50e999f56b2534.

**Pull request closed without merging**
